import type { ShellOverview } from "./domain";

export const previewShellOverview: ShellOverview = {
  library: [
    {
      id: "book-bianzheng",
      title: "中医诊断学 · 八纲辨证",
      sourceKind: "book",
      documentKind: "digital",
      sourcePath: "/Library/Medical/中医诊断学.pdf",
      createdAt: "2026-03-17T07:00:00.000Z",
      updatedAt: "2026-03-17T07:22:00.000Z",
      lastAttentionLabel: "第三章 · 寒热",
    },
    {
      id: "book-fangji",
      title: "方剂学整理讲义",
      sourceKind: "handout",
      documentKind: "hybrid",
      sourcePath: "/Library/Medical/方剂学讲义.pdf",
      createdAt: "2026-03-16T18:00:00.000Z",
      updatedAt: "2026-03-16T20:10:00.000Z",
      lastAttentionLabel: "补气方剂",
    },
  ],
  artifacts: [
    {
      id: "artifact-study-bianzheng",
      libraryItemId: "book-bianzheng",
      kind: "study-page",
      title: "八纲辨证学习页",
      summary: "聚焦寒热、虚实与易混淆点，适合快速回看和复习前定位。",
      relatedLibraryTitle: "中医诊断学 · 八纲辨证",
      updatedAt: "2026-03-17T07:23:00.000Z",
      updatedAtLabel: "刚刚更新",
    },
    {
      id: "artifact-review-pack",
      libraryItemId: "book-bianzheng",
      kind: "review-pack",
      title: "今晚复习包",
      summary: "围绕寒热辨别、气虚/阳虚混淆和关系图抽问。",
      relatedLibraryTitle: "中医诊断学 · 八纲辨证",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "今晚 20:30",
    },
  ],
  attention: {
    id: "primary",
    currentLibraryItemId: "book-bianzheng",
    currentLibraryTitle: "中医诊断学 · 八纲辨证",
    currentSectionKey: "chapter-03.section-02",
    currentSectionLabel: "第三章 · 寒热",
    focusSummary: "最近连续回到八纲辨证的寒热判断和气虚/阳虚混淆点。",
    concepts: ["寒热", "气虚", "阳虚", "舌象"],
    updatedAt: "2026-03-17T07:24:00.000Z",
    events: [
      {
        id: "event-1",
        libraryItemId: "book-bianzheng",
        sectionKey: "chapter-03.section-02",
        conceptKey: "寒热",
        reason: "最近 24 小时反复引用该章节和关系图。",
        weight: 0.95,
        occurredAt: "2026-03-17T07:24:00.000Z",
      },
      {
        id: "event-2",
        libraryItemId: "book-bianzheng",
        sectionKey: "chapter-03.section-02",
        conceptKey: "气虚-阳虚",
        reason: "用户连续追问该混淆点。",
        weight: 0.91,
        occurredAt: "2026-03-17T07:22:00.000Z",
      },
    ],
  },
  memories: [
    {
      id: "memory-1",
      kind: "attention-summary",
      title: "近期关注重心",
      content: "用户最近主要围绕八纲辨证的寒热、虚实关系来回切换阅读。",
      source: "attention-index",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
    {
      id: "memory-2",
      kind: "learning-pattern",
      title: "稳定混淆点",
      content: "气虚与阳虚需要优先提供关系图和邻近页段，而不是单纯摘要。",
      source: "behavior-distillation",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
  ],
  taskRuns: [
    {
      id: "task-1",
      taskType: "document-ingest",
      status: "done",
      title: "解析《中医诊断学》目录与章节边界",
      updatedAt: "2026-03-17T07:20:00.000Z",
      updatedAtLabel: "7 分钟前",
    },
    {
      id: "task-2",
      taskType: "study-artifact",
      status: "running",
      title: "生成八纲辨证学习页",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "正在运行",
    },
  ],
};

