import type { SessionSnapshot, SessionThreadSummary, ShellOverview } from "./domain";
import { primarySessionId } from "./domain";

export const previewShellOverview: ShellOverview = {
  library: [
    {
      id: "book-bianzheng",
      title: "中医诊断学 · 八纲辨证",
      sourceKind: "book",
      documentKind: "digital",
      sourcePath: "/Library/Medical/中医诊断学.pdf",
      createdAt: "2026-03-17T07:00:00.000Z",
      updatedAt: "2026-03-17T07:22:00.000Z",
      lastAttentionLabel: "第三章 · 寒热",
    },
    {
      id: "book-fangji",
      title: "方剂学整理讲义",
      sourceKind: "handout",
      documentKind: "hybrid",
      sourcePath: "/Library/Medical/方剂学讲义.pdf",
      createdAt: "2026-03-16T18:00:00.000Z",
      updatedAt: "2026-03-16T20:10:00.000Z",
      lastAttentionLabel: "补气方剂",
    },
  ],
  artifacts: [
    {
      id: "artifact-study-bianzheng",
      libraryItemId: "book-bianzheng",
      kind: "study-page",
      title: "八纲辨证学习页",
      summary: "聚焦寒热、虚实与易混淆点，适合快速回看和复习前定位。",
      body:
        "1. 寒证常见畏寒喜暖、口淡不渴、舌淡苔白，判断时先看整体偏冷的体征。\n2. 热证常见口渴喜冷饮、面赤、舌红苔黄，和寒证的取向刚好相反。\n3. 气虚偏乏力气短、自汗，阳虚在此基础上更偏畏寒肢冷，别只看“虚”而忽略“寒”。",
      relatedLibraryTitle: "中医诊断学 · 八纲辨证",
      updatedAt: "2026-03-17T07:23:00.000Z",
      updatedAtLabel: "刚刚更新",
    },
    {
      id: "artifact-review-pack",
      libraryItemId: "book-bianzheng",
      kind: "review-pack",
      title: "今晚复习包",
      summary: "围绕寒热辨别、气虚/阳虚混淆和关系图抽问。",
      body:
        "今晚先复习三件事：\n1. 用一组对照词快速区分寒证和热证。\n2. 回忆气虚与阳虚的共有点，再补上阳虚特有的畏寒肢冷。\n3. 再看一次关系图，确认寒热与虚实可以组合，而不是互相替代。",
      relatedLibraryTitle: "中医诊断学 · 八纲辨证",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "今晚 20:30",
    },
  ],
  attention: {
    id: "primary",
    currentLibraryItemId: "book-bianzheng",
    currentLibraryTitle: "中医诊断学 · 八纲辨证",
    currentSectionKey: "chapter-03.section-02",
    currentSectionLabel: "第三章 · 寒热",
    focusSummary: "最近连续回到八纲辨证的寒热判断和气虚/阳虚混淆点。",
    concepts: ["寒热", "气虚", "阳虚", "舌象"],
    updatedAt: "2026-03-17T07:24:00.000Z",
    events: [
      {
        id: "event-1",
        libraryItemId: "book-bianzheng",
        sectionKey: "chapter-03.section-02",
        conceptKey: "寒热",
        reason: "最近 24 小时反复引用该章节和关系图。",
        weight: 0.95,
        occurredAt: "2026-03-17T07:24:00.000Z",
      },
      {
        id: "event-2",
        libraryItemId: "book-bianzheng",
        sectionKey: "chapter-03.section-02",
        conceptKey: "气虚-阳虚",
        reason: "用户连续追问该混淆点。",
        weight: 0.91,
        occurredAt: "2026-03-17T07:22:00.000Z",
      },
    ],
  },
  memories: [
    {
      id: "memory-1",
      kind: "attention-summary",
      title: "近期关注重心",
      content: "用户最近主要围绕八纲辨证的寒热、虚实关系来回切换阅读。",
      source: "attention-index",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
    {
      id: "memory-2",
      kind: "learning-pattern",
      title: "稳定混淆点",
      content: "气虚与阳虚需要优先提供关系图和邻近页段，而不是单纯摘要。",
      source: "behavior-distillation",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
  ],
  taskRuns: [
    {
      id: "task-1",
      sessionId: null,
      taskType: "document-ingest",
      status: "done",
      title: "解析《中医诊断学》目录与章节边界",
      detail: "目录、章节边界和首批导航块已经落到本地索引。",
      updatedAt: "2026-03-17T07:20:00.000Z",
      updatedAtLabel: "7 分钟前",
    },
    {
      id: "task-2",
      sessionId: null,
      taskType: "study-artifact",
      status: "running",
      title: "生成八纲辨证学习页",
      detail: "正在把寒热与气虚/阳虚的混淆点整理成可回看的结构化正文。",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "正在运行",
    },
  ],
};

export const previewSessionSnapshot: SessionSnapshot = {
  session: {
    id: primarySessionId,
    title: "八纲辨证伴随会话",
    createdAt: "2026-03-17T07:18:00.000Z",
    updatedAt: "2026-03-17T07:28:00.000Z",
  },
  messages: [
    {
      id: "message-1",
      clientMessageId: "desktop-seed-1",
      sessionId: primarySessionId,
      role: "user",
      content: "把八纲辨证里寒热和气虚/阳虚的混淆点整理成一个能在手机上快速回看的结构。",
      attachments: [],
      status: "acked",
      createdAt: "2026-03-17T07:20:00.000Z",
    },
    {
      id: "message-2",
      clientMessageId: "assistant-seed-1",
      sessionId: primarySessionId,
      role: "assistant",
      content: "已经把学习页和今晚复习包排进当前会话，桌面和手机端会共享同一条任务流与结果。",
      attachments: [],
      status: "acked",
      createdAt: "2026-03-17T07:21:00.000Z",
    },
    {
      id: "message-3",
      clientMessageId: "mobile-seed-1",
      sessionId: primarySessionId,
      role: "user",
      content: "我上课拍到一张寒热关系图，等会儿从手机传上来后也想直接挂进这个会话。",
      attachments: [
        {
          id: "attachment-seed-1",
          sessionId: primarySessionId,
          fileName: "hanre-figure.jpg",
          mimeType: "image/jpeg",
          byteSize: 284320,
          storagePath: "/Users/demo/Pictures/hanre-figure.jpg",
          status: "ready",
          createdAt: "2026-03-17T07:27:00.000Z",
        },
      ],
      status: "acked",
      createdAt: "2026-03-17T07:27:30.000Z",
    },
  ],
  attachments: [
    {
      id: "attachment-seed-1",
      sessionId: primarySessionId,
      fileName: "hanre-figure.jpg",
      mimeType: "image/jpeg",
      byteSize: 284320,
      storagePath: "/Users/demo/Pictures/hanre-figure.jpg",
      status: "ready",
      createdAt: "2026-03-17T07:27:00.000Z",
    },
  ],
  jobs: [
    {
      id: "job-seed-1",
      sessionId: primarySessionId,
      kind: "attachment-ingest",
      status: "done",
      title: "整理手机上传的寒热关系图",
      detail: "图片已进入会话附件，可继续触发 OCR 或学习页更新。",
      updatedAt: "2026-03-17T07:28:00.000Z",
    },
  ],
  devices: [
    {
      deviceId: "desktop-preview",
      deviceType: "desktop",
      label: "Aliceloop Desktop",
      status: "online",
      lastSeenAt: "2026-03-17T07:28:00.000Z",
    },
    {
      deviceId: "mobile-preview",
      deviceType: "mobile",
      label: "Aliceloop Mobile",
      status: "online",
      lastSeenAt: "2026-03-17T07:27:50.000Z",
    },
  ],
  runtimePresence: {
    online: true,
    hostDeviceId: "desktop-preview",
    hostLabel: "Aliceloop Desktop",
    lastHeartbeatAt: "2026-03-17T07:28:00.000Z",
  },
  artifacts: previewShellOverview.artifacts,
  overview: previewShellOverview,
  lastEventSeq: 6,
};

export const previewSessionThreads: SessionThreadSummary[] = [
  {
    id: previewSessionSnapshot.session.id,
    title: previewSessionSnapshot.session.title,
    createdAt: previewSessionSnapshot.session.createdAt,
    updatedAt: previewSessionSnapshot.session.updatedAt,
    messageCount: previewSessionSnapshot.messages.length,
    latestMessagePreview: previewSessionSnapshot.messages.at(-1)?.content ?? null,
    latestMessageAt: previewSessionSnapshot.messages.at(-1)?.createdAt ?? null,
  },
];
