import type { SessionSnapshot, SessionThreadSummary, ShellOverview } from "./domain";
import { primarySessionId } from "./domain";

export const previewShellOverview: ShellOverview = {
  library: [
    {
      id: "runtime-notes",
      title: "Aliceloop Runtime Notes",
      sourceKind: "handout",
      documentKind: "digital",
      sourcePath: "/Library/Projects/Aliceloop/runtime-notes.md",
      createdAt: "2026-03-17T07:00:00.000Z",
      updatedAt: "2026-03-17T07:22:00.000Z",
      lastAttentionLabel: "第 3 节 · Session Stream",
    },
    {
      id: "session-sync-workshop",
      title: "Session Sync Workshop",
      sourceKind: "handout",
      documentKind: "hybrid",
      sourcePath: "/Library/Projects/Aliceloop/session-sync.pdf",
      createdAt: "2026-03-16T18:00:00.000Z",
      updatedAt: "2026-03-16T20:10:00.000Z",
      lastAttentionLabel: "多端同步",
    },
  ],
  artifacts: [
    {
      id: "artifact-runtime-summary",
      libraryItemId: "runtime-notes",
      kind: "study-page",
      title: "Runtime 结构整理页",
      summary: "聚焦 session、sandbox、artifact 和 memory 的关系，适合快速回看和后续实现前定位。",
      body:
        "1. Session、queue 和 events 组成 runtime 的真相层，负责持续状态和多端同步。\n2. Sandbox 只提供 read、grep、glob、write、edit、bash 六个执行原子命令，skills 通过它做副作用操作。\n3. Artifact、memory 和 tasks 是提交层结果，不该和底层执行 ABI 混在一起。",
      relatedLibraryTitle: "Aliceloop Runtime Notes",
      updatedAt: "2026-03-17T07:23:00.000Z",
      updatedAtLabel: "刚刚更新",
    },
    {
      id: "artifact-review-pack",
      libraryItemId: "runtime-notes",
      kind: "review-pack",
      title: "今晚复习包",
      summary: "围绕 runtime 分层、provider 接入和多端同步关系做抽问。",
      body:
        "今晚先复习三件事：\n1. 先说清 gateway、runtime core 和 sandbox 各自负责什么。\n2. 回忆为什么 policy loop 不是 workflow，而是模型面对统一状态的下一跳决策。\n3. 再看一次多端同步链路，确认 snapshot、stream 和 heartbeat 的分工。",
      relatedLibraryTitle: "Aliceloop Runtime Notes",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "今晚 20:30",
    },
  ],
  attention: {
    id: "primary",
    currentLibraryItemId: "runtime-notes",
    currentLibraryTitle: "Aliceloop Runtime Notes",
    currentSectionKey: "section-03",
    currentSectionLabel: "第 3 节 · Session Stream",
    focusSummary: "最近连续回到 session stream、sandbox 边界和 artifact 提交这几个实现点。",
    concepts: ["session", "sandbox", "artifact", "memory"],
    updatedAt: "2026-03-17T07:24:00.000Z",
    events: [
      {
        id: "event-1",
        libraryItemId: "runtime-notes",
        sectionKey: "section-03",
        conceptKey: "session-stream",
        reason: "最近 24 小时反复回到同一段同步协议设计。",
        weight: 0.95,
        occurredAt: "2026-03-17T07:24:00.000Z",
      },
      {
        id: "event-2",
        libraryItemId: "runtime-notes",
        sectionKey: "section-04",
        conceptKey: "sandbox-boundary",
        reason: "用户连续追问沙箱和 runtime core 的边界。",
        weight: 0.91,
        occurredAt: "2026-03-17T07:22:00.000Z",
      },
    ],
  },
  memories: [
    {
      id: "memory-1",
      kind: "attention-summary",
      title: "近期关注重心",
      content: "用户最近主要围绕 runtime core、provider 接入和多端同步的边界来回切换。",
      source: "attention-index",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
    {
      id: "memory-2",
      kind: "learning-pattern",
      title: "稳定混淆点",
      content: "遇到 runtime 设计问题时，优先给分层图和最小执行边界，而不是先展开大而全的流程图。",
      source: "behavior-distillation",
      updatedAt: "2026-03-17T07:25:00.000Z",
    },
  ],
  taskRuns: [
    {
      id: "task-1",
      sessionId: null,
      taskType: "document-ingest",
      status: "done",
      title: "解析 Runtime 设计笔记目录与章节边界",
      detail: "目录、章节边界和首批导航块已经落到本地索引。",
      updatedAt: "2026-03-17T07:20:00.000Z",
      updatedAtLabel: "7 分钟前",
    },
    {
      id: "task-2",
      sessionId: null,
      taskType: "study-artifact",
      status: "running",
      title: "生成 Runtime 结构整理页",
      detail: "正在把 session、sandbox 和 artifact 的边界整理成可回看的结构化正文。",
      updatedAt: "2026-03-17T07:24:00.000Z",
      updatedAtLabel: "正在运行",
    },
  ],
};

export const previewSessionSnapshot: SessionSnapshot = {
  session: {
    id: primarySessionId,
    title: "Runtime 设计伴随会话",
    createdAt: "2026-03-17T07:18:00.000Z",
    updatedAt: "2026-03-17T07:28:00.000Z",
  },
  project: null,
  messages: [
    {
      id: "message-1",
      clientMessageId: "desktop-seed-1",
      sessionId: primarySessionId,
      role: "user",
      content: "把 runtime 里 session、sandbox 和 artifact 的关系整理成一个能在手机上快速回看的结构。",
      attachments: [],
      status: "acked",
      createdAt: "2026-03-17T07:20:00.000Z",
    },
    {
      id: "message-2",
      clientMessageId: "assistant-seed-1",
      sessionId: primarySessionId,
      role: "assistant",
      content: "已经把结构整理页和今晚复习包排进当前会话，桌面和手机端会共享同一条任务流与结果。",
      attachments: [],
      status: "acked",
      createdAt: "2026-03-17T07:21:00.000Z",
    },
    {
      id: "message-3",
      clientMessageId: "mobile-seed-1",
      sessionId: primarySessionId,
      role: "user",
      content: "我拍到一张 session stream 的草图，等会儿从手机传上来后也想直接挂进这个会话。",
      attachments: [
        {
          id: "attachment-seed-1",
          sessionId: primarySessionId,
          fileName: "session-stream-diagram.jpg",
          mimeType: "image/jpeg",
          byteSize: 284320,
          storagePath: "/Users/demo/Pictures/session-stream-diagram.jpg",
          status: "ready",
          createdAt: "2026-03-17T07:27:00.000Z",
        },
      ],
      status: "acked",
      createdAt: "2026-03-17T07:27:30.000Z",
    },
  ],
  attachments: [
    {
      id: "attachment-seed-1",
      sessionId: primarySessionId,
      fileName: "session-stream-diagram.jpg",
      mimeType: "image/jpeg",
      byteSize: 284320,
      storagePath: "/Users/demo/Pictures/session-stream-diagram.jpg",
      status: "ready",
      createdAt: "2026-03-17T07:27:00.000Z",
    },
  ],
  pendingToolApprovals: [],
  resolvedToolApprovals: [],
  jobs: [
    {
      id: "job-seed-1",
      sessionId: primarySessionId,
      kind: "attachment-ingest",
      status: "done",
      title: "整理手机上传的 session 图示",
      detail: "图片已进入会话附件，可继续触发 OCR 或学习页更新。",
      updatedAt: "2026-03-17T07:28:00.000Z",
    },
  ],
  devices: [
    {
      deviceId: "desktop-preview",
      deviceType: "desktop",
      label: "Aliceloop Desktop",
      status: "online",
      lastSeenAt: "2026-03-17T07:28:00.000Z",
      capabilities: {
        browserRelay: {
          enabled: true,
          backend: "desktop_chrome",
          baseUrl: "http://127.0.0.1:39999",
          token: "preview-browser-relay-token",
          visible: true,
          healthy: true,
        },
      },
    },
    {
      deviceId: "mobile-preview",
      deviceType: "mobile",
      label: "Aliceloop Mobile",
      status: "online",
      lastSeenAt: "2026-03-17T07:27:50.000Z",
    },
  ],
  runtimePresence: {
    online: true,
    hostDeviceId: "desktop-preview",
    hostLabel: "Aliceloop Desktop",
    lastHeartbeatAt: "2026-03-17T07:28:00.000Z",
  },
  artifacts: previewShellOverview.artifacts,
  overview: previewShellOverview,
  lastEventSeq: 6,
};

export const previewSessionThreads: SessionThreadSummary[] = [
  {
    id: previewSessionSnapshot.session.id,
    title: previewSessionSnapshot.session.title,
    createdAt: previewSessionSnapshot.session.createdAt,
    updatedAt: previewSessionSnapshot.session.updatedAt,
    messageCount: previewSessionSnapshot.messages.length,
    latestMessagePreview: previewSessionSnapshot.messages.at(-1)?.content ?? null,
    latestMessageAt: previewSessionSnapshot.messages.at(-1)?.createdAt ?? null,
  },
];
