import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

async function main() {
  const tempDataDir = mkdtempSync(join(tmpdir(), "aliceloop-sandbox-data-"));
  const externalDir = mkdtempSync(join(tmpdir(), "aliceloop-sandbox-ext-"));
  process.env.ALICELOOP_DATA_DIR = tempDataDir;

  const [
    { createPermissionSandboxExecutor, SandboxViolationError },
    { listSandboxRuns },
    { createSession },
    { isAliceloopGeneratedFile, markGeneratedFileDeleted, markSessionGeneratedFile },
  ] = await Promise.all([
    import("../src/services/sandboxExecutor.ts"),
    import("../src/repositories/sandboxRunRepository.ts"),
    import("../src/repositories/sessionRepository.ts"),
    import("../src/repositories/sessionGeneratedFileRepository.ts"),
  ]);

  const sourcePath = join(externalDir, "source.txt");
  const elevatedOutputPath = join(externalDir, "elevated-note.txt");
  const outputPath = join(tempDataDir, "artifacts", "note.txt");
  const ownedDeletePath = join(tempDataDir, "artifacts", "generated-delete.txt");
  const manualFilePath = join(tempDataDir, "artifacts", "manual.txt");
  const emptyDirPath = join(tempDataDir, "artifacts", "empty-dir");
  const nonEmptyDirPath = join(tempDataDir, "artifacts", "non-empty-dir");
  const runtimeScriptPath = join(tempDataDir, "runtime-check.ts");
  const authoringSessionId = createSession("sandbox-smoke-author").id;
  const cleanupSessionId = createSession("sandbox-smoke-cleanup").id;

  writeFileSync(sourcePath, "alpha\nbeta\n", "utf8");
  writeFileSync(runtimeScriptPath, 'console.log("tsx-sandbox-ok");\n', "utf8");
  mkdirSync(join(tempDataDir, "artifacts"), { recursive: true });
  writeFileSync(manualFilePath, "manual\n", "utf8");
  mkdirSync(emptyDirPath, { recursive: true });
  mkdirSync(nonEmptyDirPath, { recursive: true });
  writeFileSync(join(nonEmptyDirPath, "keep.txt"), "keep\n", "utf8");

  const sandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke",
    extraReadRoots: [externalDir, tempDataDir],
    extraWriteRoots: [tempDataDir],
    extraCwdRoots: [tempDataDir],
    allowedCommands: ["cat", "rm", "rmdir", "tsx"],
    noteCreatedFile: (targetPath) => {
      markSessionGeneratedFile(authoringSessionId, targetPath);
    },
    canDeleteFile: (targetPath) => isAliceloopGeneratedFile(targetPath),
    noteDeletedFile: (targetPath) => markGeneratedFileDeleted(targetPath),
  });

  const cleanupSandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke-cleanup",
    extraReadRoots: [externalDir, tempDataDir],
    extraWriteRoots: [tempDataDir],
    extraCwdRoots: [tempDataDir],
    allowedCommands: ["cat", "rm", "rmdir", "tsx"],
    noteCreatedFile: (targetPath) => {
      markSessionGeneratedFile(cleanupSessionId, targetPath);
    },
    canDeleteFile: (targetPath) => isAliceloopGeneratedFile(targetPath),
    noteDeletedFile: (targetPath) => markGeneratedFileDeleted(targetPath),
  });

  const text = await sandbox.readTextFile({
    targetPath: sourcePath,
  });
  assert.equal(text, "alpha\nbeta\n");

  await sandbox.writeTextFile({
    targetPath: outputPath,
    content: text,
  });
  assert.equal(readFileSync(outputPath, "utf8"), "alpha\nbeta\n");

  await sandbox.writeTextFile({
    targetPath: ownedDeletePath,
    content: "generated\n",
  });
  assert.equal(
    isAliceloopGeneratedFile(ownedDeletePath),
    true,
    "newly generated file should be tracked for safe deletion across sessions",
  );

  const edited = await sandbox.editTextFile({
    targetPath: outputPath,
    transform: (content) => content.replace("beta", "gamma"),
  });
  assert.equal(edited, "alpha\ngamma\n");

  const rmDeleteResult = await cleanupSandbox.runBash({
    command: "rm",
    args: [ownedDeletePath],
    cwd: tempDataDir,
  });
  assert(rmDeleteResult.stdout.includes("deleted:"), "rm via bash should report deleted path");
  assert.equal(existsSync(ownedDeletePath), false, "rm via bash should remove generated files from a later session");
  assert.equal(isAliceloopGeneratedFile(ownedDeletePath), false, "deleted generated file should be removed from global ownership tracking");

  const rmdirResult = await cleanupSandbox.runBash({
    command: "rmdir",
    args: [emptyDirPath],
    cwd: tempDataDir,
  });
  assert(rmdirResult.stdout.includes("deleted:"), "rmdir via bash should report deleted path");
  assert.equal(existsSync(emptyDirPath), false, "rmdir via bash should remove empty directories");

  let blockedManualDelete = false;
  try {
    await cleanupSandbox.runBash({
      command: "rm",
      args: [manualFilePath],
      cwd: tempDataDir,
    });
  } catch (error) {
    blockedManualDelete = error instanceof SandboxViolationError;
  }
  assert.equal(blockedManualDelete, true, "rm via bash should block files that were never generated by Aliceloop");

  let blockedNonEmptyDirDelete = false;
  try {
    await cleanupSandbox.runBash({
      command: "rmdir",
      args: [nonEmptyDirPath],
      cwd: tempDataDir,
    });
  } catch (error) {
    blockedNonEmptyDirDelete = error instanceof SandboxViolationError;
  }
  assert.equal(blockedNonEmptyDirDelete, true, "rmdir via bash should block non-empty directories");

  let approvalCount = 0;
  const approvedSandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke-approved",
    extraReadRoots: [tempDataDir],
    extraWriteRoots: [tempDataDir],
    extraCwdRoots: [tempDataDir],
    allowedCommands: ["cat"],
    requestBashApproval: async () => {
      approvalCount += 1;
    },
  });

  const approvedBash = await approvedSandbox.runBash({
    command: "cat",
    args: [outputPath],
    cwd: tempDataDir,
  });
  assert.equal(approvedBash.stdout, "alpha\ngamma\n");
  assert.equal(approvalCount, 1, "bash approval hook should run before command execution");

  const bashResult = await sandbox.runBash({
    command: "cat",
    args: [outputPath],
    cwd: tempDataDir,
  });
  assert.equal(bashResult.stdout, "alpha\ngamma\n");

  const whichAliceloopResult = await sandbox.runBash({
    command: "which",
    args: ["aliceloop"],
    cwd: tempDataDir,
  });
  assert.equal(whichAliceloopResult.stdout.trim().length > 0, true, "which should find the injected aliceloop shim on PATH");

  const aliceloopConfigResult = await sandbox.runBash({
    command: "aliceloop",
    args: ["--help"],
    cwd: tempDataDir,
  });
  assert.match(aliceloopConfigResult.stdout, /^Usage:/m, "aliceloop CLI should be callable inside sandbox bash");

  const shellScriptResult = await sandbox.runBash({
    command: "",
    script: "which aliceloop && aliceloop --help | head -1",
    cwd: tempDataDir,
  });
  assert.match(shellScriptResult.stdout, /aliceloop/, "shell script mode should support command chaining");
  assert.match(shellScriptResult.stdout, /^Usage:/m, "shell script mode should support pipelines");

  const lsResult = await sandbox.runBash({
    command: "ls",
    cwd: tempDataDir,
  });
  assert(lsResult.stdout.length > 0, "ls should stay standard-allowed inside the configured cwd roots");

  const grepResult = await sandbox.runBash({
    command: "grep",
    args: ["gamma", outputPath],
    cwd: tempDataDir,
  });
  assert.equal(grepResult.stdout.trim(), "gamma", "grep should be allowed for local diagnostic filtering");

  const duResult = await sandbox.runBash({
    command: "du",
    args: ["-sh", join(tempDataDir, "artifacts")],
    cwd: tempDataDir,
  });
  assert(duResult.stdout.trim().length > 0, "du should be allowed for disk-usage diagnostics");

  const swVersResult = await sandbox.runBash({
    command: "sw_vers",
    cwd: tempDataDir,
  });
  assert(swVersResult.stdout.includes("ProductName"), "sw_vers should be allowed for macOS version diagnostics");

  const sysctlResult = await sandbox.runBash({
    command: "sysctl",
    args: ["-n", "hw.ncpu"],
    cwd: tempDataDir,
  });
  assert(/^\d+$/.test(sysctlResult.stdout.trim()), "sysctl should be allowed for CPU-count diagnostics");

  const ifconfigResult = await sandbox.runBash({
    command: "ifconfig",
    cwd: tempDataDir,
  });
  assert(ifconfigResult.stdout.trim().length > 0, "ifconfig should be allowed for network diagnostics");

  const vmStatResult = await sandbox.runBash({
    command: "vm_stat",
    cwd: tempDataDir,
  });
  assert(vmStatResult.stdout.includes("Mach Virtual Memory Statistics"), "vm_stat should be allowed for memory diagnostics");

  const pmsetResult = await sandbox.runBash({
    command: "pmset",
    args: ["-g", "batt"],
    cwd: tempDataDir,
  });
  assert(pmsetResult.stdout.trim().length > 0, "pmset should be allowed for battery diagnostics");

  const networksetupResult = await sandbox.runBash({
    command: "networksetup",
    args: ["-listallhardwareports"],
    cwd: tempDataDir,
  });
  assert(networksetupResult.stdout.trim().length > 0, "networksetup should be allowed for network hardware diagnostics");

  const topResult = await sandbox.runBash({
    command: "top",
    args: ["-l", "1", "-s", "0", "-n", "0"],
    cwd: tempDataDir,
  });
  assert(topResult.stdout.trim().length > 0, "top should be allowed for quick system overview diagnostics");

  const lsofResult = await sandbox.runBash({
    command: "lsof",
    args: ["-p", String(process.pid)],
    cwd: tempDataDir,
  });
  assert(lsofResult.stdout.trim().length > 0, "lsof should be allowed for process and port diagnostics");

  let blockedOutsideCwd = false;
  try {
    await sandbox.runBash({
      command: "ls",
      cwd: "/etc",
    });
  } catch (error) {
    blockedOutsideCwd = error instanceof SandboxViolationError;
  }
  assert.equal(blockedOutsideCwd, true, "bash should block cwd values outside the configured cwd roots");

  const originalPath = process.env.PATH;
  process.env.PATH = "";
  try {
    const tsxResult = await sandbox.runBash({
      command: "tsx",
      args: [runtimeScriptPath],
      cwd: tempDataDir,
    });
    assert(tsxResult.stdout.includes("tsx-sandbox-ok"), "sandbox should resolve tsx without relying on PATH");
  } finally {
    process.env.PATH = originalPath;
  }

  const homebrewNodePath = "/opt/homebrew/bin/node";
  if (existsSync(homebrewNodePath)) {
    const absoluteNodeResult = await sandbox.runBash({
      command: homebrewNodePath,
      args: ["-e", `console.log("absolute-node-ok")`],
      cwd: tempDataDir,
    });
    assert.equal(absoluteNodeResult.stdout.trim(), "absolute-node-ok");
  }

  const homebrewNpmPath = "/opt/homebrew/bin/npm";
  if (existsSync(homebrewNpmPath)) {
    const absoluteNpmResult = await sandbox.runBash({
      command: homebrewNpmPath,
      args: ["-v"],
      cwd: tempDataDir,
    });
    assert.equal(absoluteNpmResult.stdout.trim().length > 0, true);
  }

  if (existsSync(process.execPath)) {
    const execPathResult = await sandbox.runBash({
      command: process.execPath,
      args: ["-e", `console.log("process-exec-ok")`],
      cwd: tempDataDir,
    });
    assert.equal(execPathResult.stdout.trim(), "process-exec-ok");
  }

  const voltaNodePath = join(homedir(), ".volta/bin/node");
  if (existsSync(voltaNodePath)) {
    const voltaNodeResult = await sandbox.runBash({
      command: voltaNodePath,
      args: ["-e", `console.log("volta-node-ok")`],
      cwd: tempDataDir,
    });
    assert.equal(voltaNodeResult.stdout.trim(), "volta-node-ok");
  }

  const nvmVersionsDir = join(homedir(), ".nvm/versions/node");
  if (existsSync(nvmVersionsDir)) {
    const nvmNodePath = readdirSync(nvmVersionsDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => join(nvmVersionsDir, entry.name, "bin", "node"))
      .find((candidate) => existsSync(candidate));

    if (nvmNodePath) {
      const nvmNodeResult = await sandbox.runBash({
        command: nvmNodePath,
        args: ["-e", `console.log("nvm-node-ok")`],
        cwd: tempDataDir,
      });
      assert.equal(nvmNodeResult.stdout.trim(), "nvm-node-ok");
    }
  }

  let blockedHostRead = false;
  try {
    await sandbox.readTextFile({
      targetPath: "/etc/hosts",
    });
  } catch (error) {
    blockedHostRead = error instanceof SandboxViolationError;
  }
  assert.equal(blockedHostRead, true, "development mode should block host reads outside allowed read roots");

  let blockedHostBashRead = false;
  try {
    await sandbox.runBash({
      command: "cat",
      args: ["/etc/hosts"],
      cwd: tempDataDir,
    });
  } catch (error) {
    blockedHostBashRead = error instanceof SandboxViolationError;
  }
  assert.equal(blockedHostBashRead, true, "development mode should block bash reads outside allowed read roots");

  let blockedBash = false;
  try {
    await sandbox.runBash({
      command: "osascript",
      args: ["-e", "display dialog \"hi\""],
      cwd: tempDataDir,
    });
  } catch (error) {
    blockedBash = error instanceof SandboxViolationError;
  }
  assert.equal(blockedBash, true, "development mode should still block out-of-policy bash without elevated approval");

  let elevatedApprovalCount = 0;
  const elevatedSandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke-elevated",
    extraCwdRoots: [tempDataDir],
    allowedCommands: ["cat"],
    requestElevatedApproval: async () => {
      elevatedApprovalCount += 1;
    },
  });

  const elevatedHosts = await elevatedSandbox.readTextFile({
    targetPath: "/etc/hosts",
  });
  assert(elevatedHosts.length > 0, "development mode should allow host reads through single elevated approval");

  await elevatedSandbox.writeTextFile({
    targetPath: elevatedOutputPath,
    content: "elevated-write\n",
  });
  assert.equal(readFileSync(elevatedOutputPath, "utf8"), "elevated-write\n");

  const elevatedBash = await elevatedSandbox.runBash({
    command: "/bin/echo",
    args: ["elevated-bash-ok"],
    cwd: tempDataDir,
  });
  assert.equal(elevatedBash.stdout.trim(), "elevated-bash-ok");
  const elevatedBashRead = await elevatedSandbox.runBash({
    command: "cat",
    args: ["/etc/hosts"],
    cwd: tempDataDir,
  });
  assert(elevatedBashRead.stdout.length > 0, "bash reads outside roots should also require single elevated approval");
  assert.equal(elevatedApprovalCount, 3, "out-of-policy read, write, and bash actions should each require their own approval");

  let fullAccessApprovalCount = 0;
  const fullAccessSandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke-full-access",
    permissionProfile: "full-access",
    requestBashApproval: async () => {
      fullAccessApprovalCount += 1;
    },
  });

  const fullAccessHosts = await fullAccessSandbox.readTextFile({
    targetPath: "/etc/hosts",
  });
  assert(fullAccessHosts.length > 0, "full access sandbox should read arbitrary host files");

  const fullAccessBash = await fullAccessSandbox.runBash({
    command: "/bin/echo",
    args: ["full-access-ok"],
    cwd: process.cwd(),
  });
  assert.equal(fullAccessBash.stdout.trim(), "full-access-ok");
  assert.equal(fullAccessApprovalCount, 0, "full access should not require per-command bash approval");

  const fullAccessScriptPath = join(tmpdir(), `aliceloop-full-access-script-${Date.now()}.txt`);
  const fullAccessScriptSandbox = createPermissionSandboxExecutor({
    label: "sandbox-smoke-full-access-script",
    permissionProfile: "full-access",
    workspaceRoot: tempDataDir,
  });
  const fullAccessScriptResult = await fullAccessScriptSandbox.runBash({
    command: "",
    script: `printf 'full-access-script-ok' > ${fullAccessScriptPath} && cat ${fullAccessScriptPath}`,
    cwd: externalDir,
  });
  assert.equal(
    fullAccessScriptResult.stdout.trim(),
    "full-access-script-ok",
    "full-access script mode should allow redirection and host paths outside the workspace root",
  );
  assert.equal(
    readFileSync(fullAccessScriptPath, "utf8"),
    "full-access-script-ok",
    "full-access script mode should write files outside the workspace root when requested",
  );
  const fullAccessScriptPolicy = fullAccessScriptSandbox.describePolicy();
  assert.deepEqual(fullAccessScriptPolicy.allowedReadRoots, ["<all>"], "full access should not keep workspace read boundaries");
  assert.deepEqual(fullAccessScriptPolicy.allowedWriteRoots, ["<all>"], "full access should not keep workspace write boundaries");
  assert.deepEqual(fullAccessScriptPolicy.allowedCwdRoots, ["<all>"], "full access should not keep workspace cwd boundaries");

  await fullAccessSandbox.deletePath({
    targetPath: manualFilePath,
  });
  assert.equal(existsSync(manualFilePath), false, "full access should delete arbitrary host-user files");

  await fullAccessSandbox.deletePath({
    targetPath: nonEmptyDirPath,
  });
  assert.equal(existsSync(nonEmptyDirPath), false, "full access should delete non-empty directories recursively");

  const logs = listSandboxRuns(50);
  assert(logs.some((run) => run.primitive === "read" && run.status === "done"), "read run should be logged");
  assert(logs.some((run) => run.primitive === "write" && run.status === "done"), "write run should be logged");
  assert(logs.some((run) => run.primitive === "edit" && run.status === "done"), "edit run should be logged");
  assert(logs.some((run) => run.primitive === "delete" && run.status === "done"), "delete run should be logged");
  assert(logs.some((run) => run.primitive === "bash" && run.status === "done"), "bash run should be logged");
  assert(logs.some((run) => run.command === "tsx" && run.status === "done"), "tsx run should be logged");
  assert(logs.some((run) => run.status === "blocked"), "blocked run should be logged");
  assert(logs.some((run) => run.detail.includes("[elevated]") && run.status === "done"), "elevated runs should be logged");

  // ─── Seatbelt (macOS sandbox-exec) tests ───
  const { isSeatbeltAvailable } = await import("../src/runtime/sandbox/seatbelt.ts");
  const seatbeltAvailable = isSeatbeltAvailable();
  console.log(`seatbelt available: ${seatbeltAvailable}`);

  if (seatbeltAvailable) {
    const seatbeltWriteDir = mkdtempSync(join(tmpdir(), "aliceloop-seatbelt-write-"));
    const seatbeltForbiddenDir = join(homedir(), "seatbelt-smoke-forbidden-" + Date.now());

    // Seatbelt sandbox: development mode with node allowed
    const seatbeltSandbox = createPermissionSandboxExecutor({
      label: "sandbox-smoke-seatbelt",
      extraReadRoots: [tempDataDir, seatbeltWriteDir],
      extraWriteRoots: [tempDataDir, seatbeltWriteDir],
      extraCwdRoots: [tempDataDir, seatbeltWriteDir],
      allowedCommands: ["node"],
    });

    // Test 1: Network should be blocked by seatbelt in development mode
    let seatbeltNetworkBlocked = false;
    try {
      const netResult = await seatbeltSandbox.runBash({
        command: "node",
        args: ["-e", `
          const http = require("http");
          const req = http.get("http://example.com", () => { process.exit(0); });
          req.on("error", (e) => { console.error(e.message); process.exit(1); });
          setTimeout(() => process.exit(1), 5000);
        `],
        cwd: tempDataDir,
        timeoutMs: 10_000,
      });
      // If the process exits with code 1 (error), stderr will have the error
      seatbeltNetworkBlocked = netResult.stderr.length > 0;
    } catch {
      // Command failed = network was blocked
      seatbeltNetworkBlocked = true;
    }
    assert.equal(seatbeltNetworkBlocked, true, "seatbelt should block network access in development mode");

    // Test 2: File write outside allowed roots should be blocked by seatbelt kernel enforcement
    const seatbeltForbiddenFile = join(seatbeltForbiddenDir, "bad.txt");
    let seatbeltWriteBlocked = false;
    try {
      // Use elevated sandbox to bypass app-layer policy, testing kernel-layer enforcement
      const seatbeltElevatedSandbox = createPermissionSandboxExecutor({
        label: "sandbox-smoke-seatbelt-elevated",
        extraReadRoots: [tempDataDir],
        extraWriteRoots: [tempDataDir],
        extraCwdRoots: [tempDataDir],
        allowedCommands: ["node"],
        requestElevatedApproval: async () => {},
      });
      await seatbeltElevatedSandbox.runBash({
        command: "node",
        args: ["-e", `require("fs").mkdirSync("${seatbeltForbiddenDir}", {recursive:true}); require("fs").writeFileSync("${seatbeltForbiddenFile}", "bad")`],
        cwd: tempDataDir,
        timeoutMs: 10_000,
      });
      seatbeltWriteBlocked = !existsSync(seatbeltForbiddenFile);
    } catch {
      seatbeltWriteBlocked = true;
    }
    assert.equal(seatbeltWriteBlocked, true, "seatbelt should block file writes outside allowed roots at kernel level");

    // Test 3: Allowed write should succeed under seatbelt
    const seatbeltAllowedFile = join(seatbeltWriteDir, "ok.txt");
    await seatbeltSandbox.runBash({
      command: "node",
      args: ["-e", `require("fs").writeFileSync("${seatbeltAllowedFile}", "seatbelt-ok")`],
      cwd: seatbeltWriteDir,
    });
    assert.equal(readFileSync(seatbeltAllowedFile, "utf8"), "seatbelt-ok", "seatbelt should allow writes to permitted roots");

    // Test 4: full-access mode should NOT use seatbelt
    const fullAccessSeatbeltSandbox = createPermissionSandboxExecutor({
      label: "sandbox-smoke-seatbelt-full",
      permissionProfile: "full-access",
      allowedCommands: ["node"],
    });
    const fullAccessNetResult = await fullAccessSeatbeltSandbox.runBash({
      command: "node",
      args: ["-e", `console.log("full-access-seatbelt-bypass")`],
      cwd: process.cwd(),
    });
    assert.equal(
      fullAccessNetResult.stdout.trim(),
      "full-access-seatbelt-bypass",
      "full-access mode should not apply seatbelt restrictions",
    );

    console.log("seatbelt tests: all passed");
  } else {
    console.log("seatbelt tests: skipped (not macOS or sandbox-exec not found)");
  }

  console.log(
    JSON.stringify(
      {
        ok: true,
        tempDataDir,
        externalDir,
        logCount: logs.length,
      },
      null,
      2,
    ),
  );
}

void main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
